### ISSUE TITLE
[BUG] - CLI: upgrade command gives a error

### ISSUE THREAD

**Issue by withden** [nextui-org/nextui-cli#32]
### NextUI CLI Version

0.1.5

### Describe the bug

Hi,

When i use the `nextui upgrade` command, it gives me this error:

TypeError: Cannot destructure property 'install' of 'ue(...)' as it is undefined.
    at Command.Et (file:///home/denish/.nvm/versions/node/v18.18.2/lib/node_modules/nextui-cli/dist/index.js:75:1425)
    at async Command.parseAsync (/home/denish/.nvm/versions/node/v18.18.2/lib/node_modules/nextui-cli/node_modules/commander/lib/command.js:935:5)

Thanks 

### Steps to Reproduce the Bug or Issue

1. Just using `nextui upgrade` with little old component versions

### Expected behavior

It will upgrade to the latest version 

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui-cli/assets/57515871/b7bbcc76-b2d0-4e0f-a769-879d1efbbea9)

### Operating System Version

Ubuntu 23.04 (Linux - Kernal 6.5.0-26-generic)

**Comment by winchesHe** [comment]
@withden Hi, thx your feedback, could you provide your package.json and which package manager using now
