### ISSUE TITLE
Command ` npx nextui-cli@latest` not work WSL

### ISSUE THREAD

**Issue by castrogarciajs** [nextui-org/nextui-cli#43]
### NextUI CLI Version

I have not been able to install it

### Describe the bug

I run the command ` npx nextui-cli@latest` and it fires a node:internal

### Steps to Reproduce the Bug or Issue

1. Run **npx nextui-cli@lates**
2. Download nextui-cli...

```log
➜ ~  ✗ npx nextui-cli@latest
Need to install the following packages:
nextui-cli@0.1.5
Ok to proceed? (y) y
node:internal/modules/cjs/loader:1143
  const err = new Error(message);
              ^

Error: Cannot find module 'retry'
Require stack:
- /home/sebastian/.npm/_npx/8a2bbc96f792a803/node_modules/async-retry/lib/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/home/sebastian/.npm/_npx/8a2bbc96f792a803/node_modules/async-retry/lib/index.js:2:15)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at cjsLoader (node:internal/modules/esm/translators:366:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/sebastian/.npm/_npx/8a2bbc96f792a803/node_modules/async-retry/lib/index.js'
  ]
}

Node.js v20.12.2
➜ ~  ✗
```

### Expected behavior

I was expecting an installation exit or asking if I want to install nextui-cli

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui-cli/assets/116913262/4c28df4e-5148-40d2-9c23-a6fabb870738)

![image](https://github.com/nextui-org/nextui-cli/assets/116913262/4ba8be14-86c3-4ac7-9e58-f6e05074e4f1)

### Operating System Version

Windows with WSL

**Comment by winchesHe** [comment]
@castrogarciajs Hi, could you try global install? Like `npm i -g nextui-cli` and run `nextui-cli`

**Comment by castrogarciajs** [comment]
Yes, of course. But I not have a good result

## Logs

![image](https://github.com/nextui-org/nextui-cli/assets/116913262/7d01a16b-130a-41a9-8811-2298cd3946f6)


## Logs text

```log
➜ ~  npm i -g nextui-cli

added 69 packages in 6s

26 packages are looking for funding
  run `npm fund` for details

➜ ~  nextui
nextui: command not found

➜ ~  ✗ nextui-cli
nextui-cli: command not found

➜ ~  ✗ next-ui --help
next-ui: command not found
```

**Comment by winchesHe** [comment]
I think this is a problem with the configuration of environment variables in WSL, you can try this solution

1. Modify the configuration file for global environment variables: vim/etc/profile (requires root privileges)

2. Add the following content:

```shell
export NODE_HOME=/usr/app/node-v10.15.1-linux-x64 (change to your node path)
export PATH=$NODE_HOME/bin:$PATH
```

3. Save and `source /etc/profile`

**Comment by castrogarciajs** [comment]
Thank you, It work
