### ISSUE TITLE
[Feature Request] Upgrade command add option --major --minor --patch

### ISSUE THREAD

**Issue by winchesHe** [nextui-org/nextui-cli#44]
### Is your feature request related to a problem? Please describe.

1. Choose a version to upgrade detech

### Describe the solution you'd like

1. Run nextui-cli upgrade --major/--minor/--patch default --minor
2. If option `major`, then detech all updatable versions
3.  If option `minor`, then detech `minor patch` updatable versions (default)
4. If option `patch`, then detech `patch` updatable versions

Refference: https://github.com/antfu-collective/taze?tab=readme-ov-file

### Describe alternatives you've considered

No

**Comment by hasmokan** [comment]
I would like to work on this issue。

**Comment by wingkwong** [comment]
@hasmokan assigned. free feel to contact the team members in Discord if you have any questions.

**Comment by hasmokan** [comment]
When I run dev locally and use the upgrade command, even though the version of components is not the latest, it shows that they are already up to date.
![image](https://github.com/nextui-org/nextui-cli/assets/112612128/24b8942c-6f50-403e-b2e5-0e03bbe8ab10)
![image](https://github.com/nextui-org/nextui-cli/assets/112612128/b02b7c9d-de64-42a3-9fcd-6202e305eec9)
maybe in **src/helpers/package.ts**  ,this code changes version of component?
![image](https://github.com/nextui-org/nextui-cli/assets/112612128/791507ab-b16b-4d77-bb6c-4c9d957aecf6)

**Comment by winchesHe** [comment]
@hasmokan Thx, i will take a look

**Comment by hasmokan** [comment]
@winchesHe once merged, I will continue

**Comment by winchesHe** [comment]
@hasmokan Merged
