### ISSUE TITLE
[Feature Request] Add -w write option in upgrade command

### ISSUE THREAD

**Issue by winchesHe** [nextui-org/nextui-cli#55]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

1. Add option `-w --write` in upgrade
Just write upgrade version in pkg file don't run command to install

Referrence: https://github.com/antfu/taze?tab=readme-ov-file

### Describe alternatives you've considered

No

**Comment by wingkwong** [comment]
@kent99821 any update?

**Comment by winchesHe** [comment]
@kent99821 Don't worry, welcome back anytime
