### ISSUE TITLE
[BUG] - Create Next App Next UI Template Errors on Invalid Github URL

### ISSUE THREAD

**Issue by MichaelrMentele** [nextui-org/nextui-cli#71]
### NextUI CLI Version

0.3.0

### Describe the bug

When running npx create-next-app -e https://github.com/nextui-org/next-app-template

```
(base) ➜  nextui-test npx create-next-app -e https://github.com/nextui-org/next-app-template
✔ What is your project named? … my-app
Found invalid GitHub URL: "https://github.com/nextui-org/next-app-template". Please fix the URL and try again.
```

### Steps to Reproduce the Bug or Issue

1. install nextui cli 
2. npx create-next-app -e https://github.com/nextui-org/next-app-template

### Expected behavior

I expect the next-app-template to proceed with normal next app setup

### Operating System Version

macOS

**Comment by winchesHe** [comment]
@MichaelrMentele 

`npx create-next-app -e https://github.com/nextui-org/next-app-template` it work for me, it's not a nextui-cli problem, just use create-next-app directly or use `npx nextui-cli init` to create `next-app-template`

<img width="619" alt="image" src="https://github.com/nextui-org/nextui-cli/assets/96854855/8cd18a85-1c28-4754-92a8-82b07b5c73a2">
