### ISSUE TITLE
[BUG] - CAN NOT INIT PROJECT: RENAME  FAILED

### ISSUE THREAD

**Issue by fukemy** [nextui-org/nextui-cli#96]
### NextUI Version

2

### Describe the bug

nextui init next-website

NextUI CLI v0.3.4

┌  Create a new project
│
◇  Select a template (Enter to select)
│  App
│
◇  New project name (Enter to skip with default name)
│  next-website
│
◇  Select a package manager (Enter to select)
│  npm
│
└  Template creation failed

└  rename Error: Error: ENOENT: no such file or directory, rename '/Users/abc/Desktop/folder/next-app-template-main' -> '/Users/abc/Desktop/folder/next-website'

### Steps to Reproduce the Bug or Issue

see above

### Expected behavior

see above

### Operating System Version

macos

### Browser

Other (add additonal context)

**Comment by winchesHe** [comment]
will be fixed after  https://github.com/nextui-org/nextui-cli/pull/98 merged

**Comment by yueqianzhang** [comment]
My company's internal network environment can only access the internet through a proxy. The shell has environment variables set, but they are not taking effect. After checking, it might be related to this [link to GitHub - nodejs/undici](https://github.com/nodejs/undici?tab=readme-ov-file#undicifetchinput-init-promise). Can this issue be resolved?
